---
- hosts: all

  tasks:
    - name: Install Node.js and the packages required
      ansible.builtin.package:
        name: 
          - nodejs
          - npm
        state: present

    - name: Clone the application from the repo
      ansible.builtin.git:
        repo: "{{ app_repo }}"
        dest: "{{ ENV['HOME'] }}/sudoku"

    - name: Install the application dependencies
      ansible.builtin.command:
        cmd: "npm install"
        chdir: "{{ ENV['HOME'] }}/sudoku"

    - name: Start the application
      ansible.builtin.command:
        cmd: "npm start"
        chdir: "{{ ENV['HOME'] }}/sudoku"

    - name: Check if the application is running
      ansible.builtin.uri:
        url: "http://localhost:3000"
        return_content: true
      register: output
    
    - debug:
        var: output.content