- name: Create and deploy a basic index.html
  hosts: all

  tasks:
    - name: Ensure site path exists
      ansible.builtin.file:
        path: /var/www/site
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create virtualHost for apache with content
      ansible.builtin.copy:
        content: |
          <VirtualHost *:80>
            ServerAdmin webmaster@localhost
            ServerName {{ ansible_host }}
            ServerAlias www.{{ ansible_host }}
            DocumentRoot /var/www/site
            ErrorLog ${APACHE_LOG_DIR}/error.log
            CustomLog ${APACHE_LOG_DIR}/access.log combined
          </VirtualHost>
        dest: /etc/apache2/sites-available/site.conf
        owner: root
        group: root
        mode: '0644'


    - name: Create a simple index.html in ubuntu for apache2
      ansible.builtin.copy:
        content: |
          <html>
            <head>
              <title>{{ welcome_title }}</title>
            </head>
            <body>
              <h1>{{ welcome_message }}</h1>
            </body>
          </html>l
        dest: /var/www/site/index.html
        owner: root
        group: root
        mode: '0644'
      notify: restart apache service

    - name: Enable new site
      ansible.builtin.shell: /usr/sbin/a2ensite site.conf
      notify: reload apache service

    - name: Disable default Apache site
      ansible.builtin.shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: reload apache service

    - name: Show url for accessing the apache server
      ansible.builtin.debug:
        msg: You can access the server at http://{{ ansible_host }}:80

    - name: Test connection to recently configured server
      ansible.builtin.uri:
        url: http://{{ ansible_host }}:80
        status_code: 200
      register: result
      until: result.status == 200
      retries: 3
      delay: 10

    - name: Show test connection result
      ansible.builtin.debug:
        msg: Connection to server was successful
      when: result.status == 200

  handlers:
    - name: restart apache service
      ansible.builtin.service:
        name: apache2
        state: reloaded

