---
- hosts: all

  tasks:
    - name: Set fact for home directory
      ansible.builtin.set_fact:
        home_dir: "{{ lookup('env', 'HOME') }}"

    - name: Install Node.js and the packages required
      ansible.builtin.package:
        name: 
          - nodejs
          - npm
          - git
        state: present

    - name: Clone the application from the repo
      ansible.builtin.git:
        repo: "{{ app_repo }}"
        dest: "{{ home_dir }}/sudoku"

    - name: Install the application dependencies
      ansible.builtin.command:
        cmd: "npm install"
        chdir: "{{ home_dir }}/sudoku"

    - name: Start the application
      ansible.builtin.command:
        cmd: "npm start"
        chdir: "{{ home_dir }}/sudoku"

    - name: Check if the application is running
      ansible.builtin.uri:
        url: "http://localhost:3000"
        return_content: true
      register: output
    
    - debug:
        var: output.content