---
- name: Install httpd and create a basic index.html
  host: all
  tasks:
    - name: Install httpd package
      ansible.builtin.package:
        name: httpd
        state: present

    - name: Ensure httpd service is enabled and running
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Create a simple index.html with a funny message to display
      ansible.builtin.copy:
        content: |
          <html>
            <head>
              <title>Test Page</title>
            </head>
            <body>
              <h1>Hello World!</h1>
            </body>
          </html>
        dest: /var/www/html/index.html

