---
- name: Subscribe instances
  hosts: all
  gather_facts: false

  pre_tasks:
    - name: Wait for SSH connection to the new EC2 instance
      ansible.builtin.wait_for_connection:
        timeout: 300

  tasks:
    - name: Subscribe machines with susbcription manager
      community.general.redhat_subscription:
        state: present
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
        auto_attach: true

    - command: subscription-manager config --rhsm.manage_repos=1

