---
- name: Subscribe instances
  hosts: all

  tasks:
    - name: Subscribe machines with susbcription manager
      community.general.redhat_subscription:
        state: present
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
        auto_attach: true

    - command: subscription-manager config --rhsm.manage_repos=1

